[package]
name = "bbox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hecs = "0.9.1"
log = "0.4.17"
rudp = "0.2.1"
once_cell = "1.17.0"
nalgebra = "0.32.1"
parry2d = "0.13.0"
fastrand = "1.8.0"
