[abilities.assault-rifle]
name = "Assault Rifle"
icon = "assault-rifle.jpg"

[abilities.shotgun]
name = "Shotgun"
icon = "shotgun.jpg"

[abilities.sniper]
name = "Sniper Rifle"
icon = ""

[abilities.dual-gun]
name = "Laser Guns"
icon = "dual-gun.jpg"

[abilities.heal]
name = "Love Potion"
icon = "heal.jpg"

[abilities.push]
name = "Almighty Push"
icon = "push.jpg"

[abilities.time-freeze]
name = "ZA WARUDO"
icon = "time-freeze.jpg"

[abilities.shield]
name = "Shield"
icon = "shield.jpg"

[abilities.bubble-shield]
name = "Force Field"
icon = "bubble-shield.jpg"

[abilities.grappling]
name = "ODM Gear"
icon = "grappling.jpg"

[abilities.lightning]
name = "EL THOR"
icon = "lightning.jpg"